Don't redirect user to login page if logged in
auth0-samples/auth0-laravel-php-web-app pull request #37
Opened 2019-10-21 17:53 UTC by xaoseric

If a user is logged in, this prevents the login method from being called again and simply redirects the user.

2019-10-22 13:16 UTC, joshcanhelp requested changes
@xaoseric - Thank you once again! Minor change in the flow here and I'll get this merged 👍

2019-10-22 13:16 UTC, joshcanhelp commented on 01-Login/app/Http/Controllers/Auth/Auth0IndexController.php
> +        if (!auth()->check()) {
Let's switch this to `auth()->check()` and redirect if that's true.

2019-10-22 13:16 UTC, joshcanhelp commented on 01-Login/app/Http/Controllers/Auth/Auth0IndexController.php
> +        } else {
No need for an else

2019-10-22 14:22 UTC, xaoseric commented
The changes requested have been made, I also noticed that there was an else in the profile method, fixed that up as well

2019-10-22 15:05 UTC, joshcanhelp approved these changes
@xaoseric Thank you!

Is there a reason why `auth()` is used in one place and `\Auth` in another?

2020-10-13 20:18 UTC, evansims commented
Suggested changes have been rolled into #48, thank you

2020-10-13 20:18 UTC, closed without merging